project:
  type: website
  output-dir: docs

website:
  title: "Alexandre Loureiro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
      - research.qmd
      - href: short_cv.qmd
        text: "CV"
  favicon: "images/loureiro_picture.jpeg"
  
format:
  html:
    toc: true
    theme: spacelab
    css: styles.css
    smooth-scroll: true