---
title: "About"
---

I was born and raised in Recife, Brazil. I, therefore, could never escape (and in fact I did not want to!) the full majesty of life in the tropics. It is everywhere you look, and everywhere you go. I, in particular, was completely obsessed with the leaf-cutter ants that created mighty civilizations in my front yard to my absolute delight, and my mothers absolute dismay, because it meant her much cared-for garden now had its days numbered. After a high school exchange trip to Nova Scotia, Canada, and a subsequent scholarship to Dalhousie University, I moved to Canada in 2012 to pursue a BSc in Agriculture with a major in environmental sciences.

During my Time at Dalhousie University, I got involved in <a href="https://www.dal.ca/faculty/agriculture/plant-food-env/faculty-staff/our-faculty/christopher-cutler.html" target="_blank">Dr. Chris Cutler</a>'s entomology laboratory, where I started as a volunteer research assistant in my first year, and then was hired as a summer research assistant for every summer until I started my Masters. In my MSc, also under Dr. Cutler's supervision, I was finally in charge of a large-scale project, and it was at that time that I fell in love with statistics. I went from having a self-declared dislike for it, to wanting to learn about it more and more, to literally "spreading the good news" to my friends. I quickly became the "stats guy" for my lab and I have maintained this reputation ever since. Aside from stats, I got to learn a lot about ecology, community ecology, and the Carabidae fauna found in lowbush blueberry fields, but as I said earlier, my "gateway drug" into biology were ants, so I went looking for some kind of ant project for my PhD.

It was thus that I came across <a href="https://www.malexsmith.com" target="_blank">Dr. Alex Smith</a> on my Google searches for ant researchers in Canada. I promptly fired him an email explaining to him just how much I love ants and how I would love to work with him. After some email exchanges and video calls, I started my PhD at the University of Guelph under Dr. Smith's supervision. I was Costa Rica bound, as all of my field work was going to happen there, but somehow, he convinced me to work with beetles again (rove beetles this time) instead of ants! Once the COVID-19 pandemic hit, however, and all field trips cancelled for the foreseeable future, I needed to re-design some of my work, which meant now I was going to do field work at local woods in Guelph, and, wouldn't you know it, meant that I was finally going to work with ants!

In my PhD work (which is ongoing) I'm learning more about how abiotic variables (temperature, humidity, and elevation) and corresponding physiological traits for ants and beetles (thermal tolerance and cuticular hydrocarbons) explain (or not!) their community distribution in space.
