---
title: "Curriculum Vitae"
---

My detailed CV is available upon <a href="mailto:a.loureiro@uoguelph.ca" target="_blank">request</a>.

## Education

- **PhD (Integrative Biology)** | University of Guelph, Guelph, Ontario, Canada | *2019-Present*
  - Focus on insect ecology
- **MSc (Agriculture)** | Dalhousie University, Truro, Nova Scotia, Canada | *2016-2018*
  - Focus on insect ecology
- **BSc (Agriculture)** | Dalhousie University, Truro, Nova Scotia, Canada | *2012-2016*
  - Major in Environmental Sciences
  - Distinction

## Work Experience

### Research

- **Summer Research Assistant** | Entomology Laboratory, Dalhousie University, Truro, Nova Scotia, Canada | *2013-2016*

### Teaching

- **Teaching Assistant** | University of Guelph, Guelph, Ontario, Canada | *2022*
  - Ecology (BIOL*2060)
- **Teaching Assistant** | University of Guelph, Guelph, Ontario, Canada | *2021*
  - Ecology (BIOL*2060)
  - Discovering Biodiversity (BIOL*1070)
- **Workplace Supervisor** | University of Guelph, Guelph, Ontario, Canada| *2020*
  - Internship in Biological Science (BIOL*3660)
- **Workplace Supervisor** | University of Guelph, Guelph, Ontario, Canada| *2019*
  - Internship in Biological Science (BIOL*3660)
- **Teaching Assistant** | University of Guelph, Guelph, Ontario, Canada | *2019*
  - Ecological Methods (BIOL*4110)
  - Laboratory and Field Studies in Ecology (BIOL*3010)
- **Invited Lecturer** | University of Guelph, Guelph, Ontario, Canada | *2019*
  - Invertebrate Morphology and Evolution (ZOO*2700)
- **Teaching Assistant** | Dalhousie University, Truro, Nova Scotia, Canada | *2018*
  - Introduction to Planned Studies: Surveys and Experiments (STAA*3000)
- **Tutor** | Dalhousie University, Truro, Nova Scotia, Canada | *2017*
  - Intermediate Statistical Methods (AGRI*5630)
- **Teaching Assistant** | Dalhousie University, Truro, Nova Scotia, Canada | *2017*
  - Intro to Soil and Soil Management (SOIL*0201)

## Publications

### Peer-Reviewed Articles

**4.** **Loureiro, A. M.**, & Nams, V. O. (2020). <a href="https://doi.org/10.4039/tce.2020.48" target="_blank">Sand and shine: an inexpensive method to measure terrestrial arthropod movement in the laboratory</a>. *The Canadian Entomologist*, 152(6), 823-829.

**3.** **Loureiro, A. M.**, Nams, V. O., White, S. N., & Cutler, G. C. (2020). <a href="https://doi.org/10.1093/ee/nvaa047" target="_blank">Short-term dispersal and long-term spatial and temporal patterns of Carabidae (Coleoptera) in lowbush blueberry fields</a>. *Environmental Entomology*, 49(3), 572-579.

**2.** **Loureiro, A. M.**, Cutler, G. C., Nams, V. O., & White, S. N. (2019). <a href="https://doi.org/10.1093/jisesa/iez027" target="_blank">*Poecilus lucublandus* (Coleoptera: Carabidae) and *Pterostichus mutus* do not feed on hair fescue, red sorrel, and poverty oatgrass seeds</a>. *Journal of Insect Science*, 19(2), 21.

**1.** **Loureiro, A. M. M. C.**, & Cutler, G. C. (2016). <a href="https://acadianes.org/journal/papers/cutler_16-4.pdf" target="_blank">Parasitism of blueberry spanworm (Lepidoptera: Geometridae) by Ichneumonidae and Tachinidae in Nova Scotia blueberry fields</a>. *Journal of the Acadadian Entomological Society*, 12, 31-34.

### Theses

Loureiro, A. M. M. C. (2018). <a href="http://hdl.handle.net/10222/74193" target="_blank">Feeding behaviour, dispersal, and community dynamics of Carabidae found in Nova Scotia lowbush blueberry fields</a>. Masters Thesis, *Dalhousie University*.

### Book Chapters

M. Alex Smith, Connor Warne, Kate Pare, Sarah Dolson, Elyssa Loewen, Kelsey Jones, Megan McPhee, Lauren Stitt, Lauren Janke, Rebecca M. Smith, Heather Coatsworth, **Alexandre M. M. C. Loureiro**, Angel Solis, Carlos F. Viquez, Josephine Rodriguez, Jose Fernandez-Triana, Michael J. Sharkey, James Whitfield, Alejandro Masís, María Marta Chavarría, Roger Blanco, Felipe Chavarria, Eugenie PhillipsRodríguez, Roberto Fernández, Dunia Garcia, Guillermo Pereira, Harry Ramirez, Manuel Pereira, Winnie Hallwachs, and Daniel H. Janzen. (2023). <a href="https://doi.org/10.1007/978-3-031-22848-3_10" target="_blank">Communities of small terrestrial arthropods change rapidly along a Costa Rican elevation gradient</a>. In *Neotropical Gradients and Their Analysis*, Springer.

## Conference Presentations

Loureiro, Alexandre M.M.C., and Smith, M. Alex. 2021. “Beetle Diversity and Elevation: What Do We Really Know?” Talk. *Entomological Society of Canada Annual Meeting*. Online (Zoom).

Loureiro, Alexandre M.M.C., and Smith, M. Alex. 2021. “Beetle Diversity and Elevation: What Do We Really Know?” Talk. *University of Guelph Graduate Student Symposium*. Online (Zoom).

Loureiro, Alexandre M.M.C., Sinclair, Brent J., Cottenie, Karl, Janzen, Daniel H., Hallwachs, Winnie, and Smith, M Alex. 2019. “Insect Diversity, Thermal Tolerance, and Thermal Regulating Adaptations Along a Neotropical Elevational Gradient.” Poster. *Entomological Society of Ontario Annual Meeting*. Bark Lake, Ontario, Canada. <https://journal.lib.uoguelph.ca/index.php/eso/article/view/6184>.

Loureiro, Alexandre M.M.C., Cutler, G. Christopher, Nams, Vilis O., and White, Scott N. 2018. “Diversity and Dispersal of Ground Beetles (Carabidae) Within Commercial Lowbush Blueberry Fields.” Talk. *Dalhousie University Graduate Research Day*. Truro, Nova Scotia, Canada.

Loureiro, Alexandre M.M.C., Cutler, G. Christopher, Nams, Vilis O., and White, Scott N. 2017. “Diversity and Dispersal of Ground Beetles (Carabidae) Within Commercial Lowbush Blueberry Fields.” Talk. *Acadian Entomological Society Annual Meeting*. Charlottetown, Prince Edward Island, Canada.

Loureiro, Alexandre M.M.C., Cutler, G. Christopher, Nams, Vilis O., and White, Scott N. 2017. “Diversity and Dispersal of Ground Beetles (Carabidae) Within Commercial Lowbush Blueberry Fields.” Talk. *Entomological Society of Canada Annual Meeting*. Winnipeg, Manitoba, Canada.

Loureiro, Alexandre M.M.C., and Cutler, G. Christopher. 2016. “Parasitism of Blueberry Spanworm (Lepidoptera: Geometridae) by Ichneumonidae and Tachinidae in Nova Scotia Blueberry Fields.” Poster. *Acadian Entomological Society Annual Meeting*. Moncton, New Brunswick, Canada.

Loureiro, Alexandre M.M.C., Sangha, Jatinder, and Cutler, G. Christopher. 2015. “Preference of Chafer Beetles (*Serica* Sp.) for Various Host Plants Found in Lowbush Blueberry Fields.” Talk. *Acadian Entomological Society Annual Meeting*. Moncton, New Brunswick, Canada.

## Academic Service

### Peer-Review for Academic Journals
- *Ecological Entomology* (Royal Entomological Society, United Kingdom)
- *Journal of the Acadian Entomological Society* (Acadian Entomological Society, Canada)

## Awards and Distinctions
  
- **Third Place (Oral Presentation)** | *2021*
  - Graduate Student Symposium, University of Guelph, Guelph, Ontario, Canada
  - $75
- **International Doctoral Tuition Scholarship** | *2019-2022*
  - Department of Integrative Biology, University of Guelph, Guelph, Ontario, Canada
  - $50,000
- **First place (Oral Presentation)** | *2018*
  - Graduate Research Day, Dalhousie University, Truro, Nova Scotia, Canada
  - $50
- **First place (Poster Presentation)** | *2016*
  - Annual General Meeting, Acadian Entomological Society, Moncton, New Brunswick, Canada
  - $50
- **Gordon B. Kinsman Memorial Graduate Scholarship** | *2016*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - $1,500
- **International Students Scholarship** | *2016*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - $500
- **Dean’s List Member** | *2012‑2016*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - Awarded in 2012, 2014, and 2016
- **National Scholar Award Canada** | *2015‑2016*
  - Canadian Collegiate Athletic Association
  - Awarded to student‑athletes who achieve honours standings while competing in intercollegiate athletics
- **National Scholar Award Canada** | *2012‑2013*
  - Canadian Collegiate Athletic Association
  - Awarded to student‑athletes who achieve honours standings while competing in intercollegiate athletics
- **All Academic Athlete** | *2012-2013*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - Athletes who have demonstrated excellence in academics and athletics, achieving GPA of 3.7 or above for “honors” and a position on a varsity team (1st semester)
- **Dean’s Scholarship** | *2012-2016*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - $40,000

## Mentorship, Leadership, and Service

- **Mentor** | *2019*
  - Integrative Biology Undergraduate Mentorship Program, Guelph, Ontario, Canada
- **Assistant Coach** | *2018*
  - Dalhousie Rams Men’s Soccer, Truro, Nova Scotia, Canada
- **Organizing Committee Member** | *2018*
  - Dalhousie BioBlitz, Truro, Nova Scotia, Canada
- **Captain** | *2016-2017*
  - Dalhousie Rams Men’s Soccer, Truro, Nova Scotia, Canada
- **Leader** | *2016-2017*
  - Global Student Community, Truro, Nova Scotia, Canada
- **President** | *2016*
  - Dalhousie Agricultural International Students Association, Truro, Nova Scotia, Canada
- **Peer Education Coordinator** | *2015*
  - Pro‑Social/Caring Campus Program, Truro, Nova Scotia, Canada
- **Orientation Leader** | *2014*
  - Dalhousie Orientation Week, Truro, Nova Scotia, Canada
- **Volunteer Coach** | *2013-2016*
  - Under‑8 Soccer, CC Riders Soccer Club, Truro, Nova Scotia, Canada
- **Volunteer Research Assistant** | *2012*
  - Entomology Laboratory, Dalhousie University, Truro, Nova Scotia, Canada
- **Volunteer Recruiter** | *2011*
  - Nova Scotia Agricultural College booth
  - Education fair, Recife, Pernambuco, Brazil

## Public Outreach

- **Committee Member** | *2020‑2022*
  - Entomological Society of Ontario
  - Social media content creation for the ESO Communications Committee
- **Organizing Committee Member** | *2019*
  - Guelph Bug Day, University of Guelph, Guelph, Ontario, Canada
- **Speaker** | *2016*
  - Agricultural Fall Fair, Halifax, Nova Scotia, Canada
  - Insect seminar for elementary school students
- **Speaker** | *2014*
  - Dalhousie Orientation Week, Truro, Nova Scotia, Canada
- **Speaker** | *2013*
  - Dalhousie University, Truro, Nova Scotia, Canada
  - Recruiting event with recruitment staff from several institutions
